model:
    arch: deeplab
task: seg
data:
    dataset: kitti
    train_split: train
    val_split: val
    img_rows: 256
    img_cols: 832
    img_norm: True
#    version: cityscapes
    path: ../pytorch-semseg/datasets/kitti/semantics

training:
    train_iters: 10000000
    batch_size: 4
    val_interval: 40
    n_workers: 2
    print_interval: 10
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: True
#    augmentations:
#        rcrop: [256, 512]
    lr_schedule:
    resume: ../pytorch-semseg/runs/deeplab_cityscapes/11044/deeplab_cityscapes_best_model.pkl
