model:
    arch: frrn
    model_type: A
task: seg
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 256
    img_cols: 512
    img_norm: True
#    version: cityscapes
    path: datasets/cityscapes
training:
    train_iters: 10000
    batch_size: 3
    val_interval: 1000
    n_workers: 2
    print_interval: 200
    optimizer:
        name: 'adam'
        lr: 1.0e-3
    loss:
        name: 'bootstrapped_cross_entropy'
        size_average: True
        K:  16384 # 512*256/8
    lr_schedule:
    resume: runs/frrnA_cityscapes_seg/94260/frrn_cityscapes_best_model.pkl
